Repository RubberDuckCrew/.github, pull requests merged in 2025-09, with the labels that each got.

#23 👷 Fix enforce branch names input
  .github/workflows/conventions.yml
Labels: 👷 CI/CD

#32 👷 Centralize actions
  .github/workflows/action-actionlint.yml
  .github/workflows/action-conventions.yml
  .github/workflows/action-docs.yml
  .github/workflows/action-sync-labels.yml
  .github/workflows/actionlint.yml
  .github/workflows/conventions.yml
  .github/workflows/docs.yml
  .github/workflows/sync-labels.yml
Labels: 👷 CI/CD

#34 👷 Auto add issue to issue tracker
  .github/workflows/action-add-issue-tracker.yml
  .github/workflows/add-issue-tracker.yml
Labels: 👷 CI/CD

#37 🔒 Update transitive dependencies
  docs/package-lock.json
  docs/package.json
Labels: 🔒️ Security

#44 👷 Centralize close actions
  .github/workflows/action-close-actions.yml
  .github/workflows/close-actions.yml
  docs/src/development/ci-cd.md
Labels: 👷 CI/CD

#48 📝 Document dependency pinning for libraries
  docs/.vitepress/config.ts
  docs/src/development/ci-cd.md
  docs/src/development/index.md
  docs/src/development/renovate.md
Labels: 📝 Documentation

#52 🔧 Set pin digest commit message
  configs/renovate/renovate-rubberduckcrew.json
Labels: 🔧 Configuration
